[package]
name = "spinhdl-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
spinhdl_core = { workspace = true }
toml = "0.9"
clap = {version = "4.5.49", features = ["derive"] }

[[bin]]
name = "spinhdl"
path = "src/main.rs"
